Repository tikv/client-rust, pull requests merged in 2021-02, with the labels that each got.

#228 Distinguish not existing key and existing key with empty value in get_for_update
  src/transaction/requests.rs
  src/transaction/transaction.rs
  tikv-client-proto/proto/kvrpcpb.proto
Labels: enhancement, status/LGT1, status/can-merge

#233 Support mutation Insert and CheckNotExists
  src/transaction/buffer.rs
  src/transaction/transaction.rs
  tests/integration_tests.rs
  tikv-client-common/src/errors.rs
Labels: contribution, first-time-contributor, status/LGT2

#232 Refactor the command abstraction
  .travis.yml
  Cargo.toml
  examples/pessimistic.rs
  mock-tikv/Cargo.toml
  rustfmt.toml
  src/backoff.rs
  src/compat.rs
  src/kv/bound_range.rs
  src/kv/key.rs
  src/kv/kvpair.rs
  src/lib.rs
  src/mock.rs
  src/pd/client.rs
  src/raw/client.rs
  src/raw/lowering.rs
  src/raw/mod.rs
  src/raw/requests.rs
  src/request.rs
  src/request/mod.rs
  src/request/plan.rs
  src/request/plan_builder.rs
  src/request/shard.rs
  src/store.rs
  src/transaction/buffer.rs
  src/transaction/client.rs
  src/transaction/lock.rs
  src/transaction/lowering.rs
  src/transaction/mod.rs
  src/transaction/requests.rs
  src/transaction/transaction.rs
  src/util/iter.rs
  src/util/mod.rs
  tests/integration_tests.rs
  tikv-client-common/Cargo.toml
  tikv-client-pd/Cargo.toml
  tikv-client-proto/Cargo.toml
  tikv-client-store/Cargo.toml
  tikv-client-store/src/errors.rs
Labels: status/LGT1
