Repository tikv/client-rust, pull requests merged in 2021-04, with the labels that each got.

#252 Fix batch_get_for_update
  src/request/mod.rs
  src/request/plan.rs
  src/request/plan_builder.rs
  src/request/shard.rs
  src/transaction/requests.rs
  src/transaction/transaction.rs
  tests/integration_tests.rs
  tikv-client-pd/src/cluster.rs
Labels: status/LGT1

#253 Fix two bugs with insert and delete
  rust-toolchain
  src/transaction/buffer.rs
  src/transaction/lowering.rs
  src/transaction/transaction.rs
  tests/integration_tests.rs
Labels: bug, status/LGT2

#259 Allow txn to rollback after commit failed
  src/transaction/transaction.rs
Labels: status/LGT1

#263 add new protocol messages for coprocessor_v2
  tikv-client-proto/proto/coprocessor_v2.proto
  tikv-client-proto/proto/tikvpb.proto
Labels: status/LGT1

#264 Remove rust-toolchain file
  rust-toolchain
Labels: status/LGT1

#265 add new protocol messages for coprocessor_v2
  mock-tikv/src/server.rs
  tikv-client-proto/proto/coprocessor_v2.proto
  tikv-client-proto/proto/tikvpb.proto
  tikv-client-proto/src/lib.rs
Labels: status/LGT2

#254 Don't set primary key in a pessimistic lock request until it succeeds
  src/transaction/buffer.rs
  src/transaction/transaction.rs
Labels: status/LGT1

#266 Don't resolve lock in raw requests
  src/raw/client.rs
Labels: status/LGT1

#258 Make get_for_update work for optimistic txns
  src/transaction/transaction.rs
  tests/integration_tests.rs
Labels: status/LGT1

#256 Remove the Mutex in Buffer
  src/transaction/buffer.rs
  src/transaction/snapshot.rs
  src/transaction/transaction.rs
  tests/integration_tests.rs
Labels: status/LGT1

#262 Support atomic operations (CAS, put, and delete)
  mock-tikv/src/pd.rs
  mock-tikv/src/server.rs
  src/raw/client.rs
  src/raw/lowering.rs
  src/raw/requests.rs
  src/request/plan.rs
  src/timestamp.rs
  tests/integration_tests.rs
  tikv-client-common/src/errors.rs
  tikv-client-pd/src/timestamp.rs
  tikv-client-proto/proto/backup.proto
  tikv-client-proto/proto/coprocessor_v2.proto
  tikv-client-proto/proto/encryptionpb.proto
  tikv-client-proto/proto/import_sstpb.proto
  tikv-client-proto/proto/kvrpcpb.proto
  tikv-client-proto/proto/metapb.proto
  tikv-client-proto/proto/pdpb.proto
  tikv-client-proto/proto/raft_cmdpb.proto
  tikv-client-proto/proto/raft_serverpb.proto
  tikv-client-proto/proto/tikvpb.proto
  tikv-client-store/src/errors.rs
  tikv-client-store/src/request.rs
Labels: status/LGT1

#269 Improve documentation
  README.md
  src/config.rs
  src/lib.rs
  src/mock.rs
  src/pd/client.rs
  src/pd/retry.rs
  src/raw/client.rs
  src/store.rs
  src/transaction/buffer.rs
  src/transaction/client.rs
  src/transaction/lock.rs
  src/transaction/requests.rs
  src/transaction/transaction.rs
Labels: status/LGT1

#271 Buffer improvements
  .travis.yml
  README.md
  src/transaction/buffer.rs
  src/transaction/transaction.rs
Labels: status/LGT1

#273 Fix 1PC panic
  src/transaction/requests.rs
Labels: status/LGT1

#268 Support multi-reigon test
  .travis.yml
  Cargo.toml
  Makefile
  config/pd.toml
  config/tikv.toml
  src/pd/retry.rs
  src/util/iter.rs
  tests/common/ctl.rs
  tests/common/mod.rs
  tests/failpoint_tests.rs
  tests/integration_tests.rs
Labels: status/LGT1
