Repository tikv/client-rust, pull requests merged in 2021-01, with the labels that each got.

#214 CI: use nightly TiKV and PD images and run examples
  .travis.yml
  examples/pessimistic.rs
  examples/transaction.rs
  tests/integration_tests.rs
  tikv-client-store/src/request.rs
Labels: status/LGT1

#213 Refactor the transaction API re how we set options, and add some options to skip resolve and retry
  examples/pessimistic.rs
  examples/transaction.rs
  src/backoff.rs
  src/config.rs
  src/lib.rs
  src/raw/client.rs
  src/raw/requests.rs
  src/request.rs
  src/transaction/client.rs
  src/transaction/lock.rs
  src/transaction/mod.rs
  src/transaction/requests.rs
  src/transaction/transaction.rs
  tests/integration_tests.rs
Labels: status/LGT2

#215 Update dependency
  .gitignore
  Cargo.lock
  Cargo.toml
  mock-tikv/Cargo.toml
  src/backoff.rs
  tests/integration_tests.rs
  tikv-client-common/Cargo.toml
  tikv-client-common/src/security.rs
  tikv-client-pd/Cargo.toml
  tikv-client-proto/Cargo.toml
  tikv-client-store/Cargo.toml
Labels: status/LGT2

#210 fix using wrong primary key
  src/transaction/buffer.rs
  src/transaction/transaction.rs
Labels: status/LGT2

#223 Refactor: fix nightly cargo clippy
  examples/raw.rs
  src/kv/bound_range.rs
  src/kv/key.rs
  src/kv/kvpair.rs
  src/kv/mod.rs
  src/lib.rs
  src/raw/client.rs
Labels: status/LGT3

#222 Add an option to control the behavior when txns get dropped
  src/transaction/transaction.rs
  tests/integration_tests.rs
Labels: status/LGT1

#219 Fix deadlock in pd cluster
  src/pd/retry.rs
Labels: status/LGT2, status/can-merge

#224 Add some comment for deadlock #219
  src/pd/retry.rs
Labels: status/LGT1

#226 Make CheckLevel public
  src/lib.rs
  src/transaction/mod.rs
Labels: status/LGT1

#221 Implement some missing API
  src/timestamp.rs
  src/transaction/requests.rs
  src/transaction/transaction.rs
  tests/integration_tests.rs
  tikv-client-common/src/errors.rs
  tikv-client-store/src/errors.rs
  tikv-client-store/src/request.rs
Labels: enhancement, status/LGT1

#218 Fix several bugs in pessimistic transaction
  .travis.yml
  README.md
  src/kv/bound_range.rs
  src/transaction/buffer.rs
  src/transaction/requests.rs
  src/transaction/transaction.rs
  tests/integration_tests.rs
  tests/mock_tikv_tests.rs
Labels: status/LGT3, status/can-merge

#229 Add key_exists method
  README.md
  examples/transaction.rs
  src/transaction/snapshot.rs
  src/transaction/transaction.rs
Labels: enhancement, status/LGT1

#231 Give examples default pd addresses
  examples/common/mod.rs
Labels: status/LGT1

#230 Fix warnings when generating docs
  .travis.yml
  src/transaction/client.rs
  src/transaction/transaction.rs
  tikv-client-common/src/errors.rs
Labels: first-time-contributor, status/LGT1
